// <auto-generated />
namespace SporApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _25052020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_25052020));
        
        string IMigrationMetadata.Id
        {
            get { return "202005251043253_25052020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
